/**
 * Extracted with Array.from(editor.ui.componentFactory.names())
 */

export type CheckEditorToolbarItem =
  | 'accessibilityHelp'
  | 'selectAll'
  | 'undo'
  | 'redo'
  | 'bold'
  | 'italic'
  | 'blockQuote'
  | 'link'
  | 'ckfinder'
  | 'uploadImage'
  | 'imageUpload'
  | 'heading'
  | 'imageTextAlternative'
  | 'insertImage'
  | 'imageInsert'
  | 'toggleImageCaption'
  | 'imageStyle:inline'
  | 'imageStyle:alignLeft'
  | 'imageStyle:alignRight'
  | 'imageStyle:alignCenter'
  | 'imageStyle:alignBlockLeft'
  | 'imageStyle:alignBlockRight'
  | 'imageStyle:block'
  | 'imageStyle:side'
  | 'imageStyle:wrapText'
  | 'imageStyle:breakText'
  | 'indent'
  | 'outdent'
  | 'numberedList'
  | 'bulletedList'
  | 'mediaEmbed'
  | 'insertTable'
  | 'tableColumn'
  | 'tableRow'
  | 'mergeTableCells';
